-- ON DELETE CASCADE & ON DELETE SET NULL 


-- DROP TABLE

DROP TABLE COLLEGE;
DROP TABLE STUDENT;

-- DISPLAY DATA FROM TABLE

SELECT * FROM COLLEGE;
SELECT * FROM STUDENT;


-- WHEN WE WANT TO CREATE TABLE THEN WE FIRST CREATE PARENT TABLE AND AFTER THAT CHILD TABLE.
-- WHEN WE WANT TO DROP TABLE THEN WE FIRST DROP CHILD TABLE AND AFTER THAT PARENT TABLE.


-- CREATE PARENT TABLE

CREATE TABLE COLLEGE
(
 	C_CODE NUMBER PRIMARY KEY,
    C_NAME VARCHAR(20)
);

-- CREATE CHILD TABLE WITHOUT USING ON DELETE CASCADE & ON DELETE SET NULL 

CREATE TABLE STUDENT 
(
	ENRRO_NO NUMBER(10) PRIMARY KEY,
    NAME VARCHAR(20),
    C_CODE NUMBER(5) REFERENCES COLLEGE
);


-- INSERT RECORDS

INSERT INTO COLLEGE VALUES(101,'Atmiya University');
INSERT INTO COLLEGE VALUES(102,'Marvadi University');
INSERT INTO COLLEGE VALUES(103,'R.K University');

INSERT INTO STUDENT VALUES(21080121,'Jack',101);
INSERT INTO STUDENT VALUES(21080122,'Lizza',101);
INSERT INTO STUDENT VALUES(21080123,'John',102);
INSERT INTO STUDENT VALUES(21080124,'Lili',103);


-- DELETE RECORD FROM PARENT TABLE

DELETE FROM COLLEGE WHERE C_CODE=103; -- IT'S GIVES ERROR LIKE : ... integrity constraint .... child record found ...
--WE CAN NOT DELETE THE RECORD FROM PARENT TABLE IF THE RECORD IN CHILD EXISTS.


-- DROP PARENT TABLE

DROP TABLE COLLEGE; -- IT'S GIVES ERROR LIKE : unique/primary keys in table referenced by foreign keys
-- WE CAN NOT DROP THE PARENT TABLE IF THE RECORD IN CHILD EXISTS.


--IF YOU WANT TO DELETE IT FORECEFULLY, THEN YOU CAN USE ON DELETE CASCADE & ON DELETE SET NULL 


-- DROP TABLE STUDENT 

DROP TABLE STUDENT;


-- CREATE CHILD TABLE USING ON DELETE CASCADE 
-- ON DELETE CASCADE MEANS WHEN WE DELETE THE RECORDS FROM PARENT TABLE, IT WILL AUTOMATICALLY DELETE RECORDS FROM THE CHILD TABLE. 

CREATE TABLE STUDENT 
(
    ENRRO_NO NUMBER(10) PRIMARY KEY,
    NAME VARCHAR(20),
    C_CODE NUMBER(5) REFERENCES COLLEGE ON DELETE CASCADE 
);

INSERT INTO STUDENT VALUES(21080121,'Jack',101);
INSERT INTO STUDENT VALUES(21080122,'Lizza',101);
INSERT INTO STUDENT VALUES(21080123,'John',102);
INSERT INTO STUDENT VALUES(21080124,'Lili',103);

DELETE FROM COLLEGE WHERE C_CODE=102; -- DELETE RECORD FROM PARENT TABLE



-- DROP TABLE STUDENT 

DROP TABLE STUDENT;


-- CREATE CHILD TABLE USING ON DELETE SET NULL  
-- ON DELETE SET NULL  MEANS WHEN WE DELETE THE RECORDS FROM PARENT TABLE, IT WILL NOT DELETE RECORDS FROM THE CHILD TABLE.

CREATE TABLE STUDENT 
(
    ENRRO_NO NUMBER(10) PRIMARY KEY,
    NAME VARCHAR(20),
    C_CODE NUMBER(5) REFERENCES COLLEGE ON DELETE SET NULL 
);

INSERT INTO STUDENT VALUES(21080121,'Jack',101);
INSERT INTO STUDENT VALUES(21080122,'Lizza',101);
INSERT INTO STUDENT VALUES(21080123,'John',102);
INSERT INTO STUDENT VALUES(21080124,'Lili',103);

DELETE FROM COLLEGE WHERE C_CODE=102; -- DELETE RECORD FROM PARENT TABLE


-- WHEN WE USE ON DELETE CASCADE THEN IT'S DELETE DATA FROM PARENT AND CHILD TABLE.

-- WHEN WE USE ON DELETE SET NULL THEN IT'S DELETE FROM PARENT TABLE ONLY.


















