CREATE TABLE Supplier (
        S_ID VARCHAR2(5) PRIMARY KEY CONSTRAINT S_ID_MUST_START_WITH_S_AND_MUST_CONTAINS_4_DIGIT CHECK (S_ID LIKE 'S____'),
        S_NAME VARCHAR2(50),
        CONTACT_NUM NUMBER(10) UNIQUE CONSTRAINT MUST_BE_ENTER_VALID_AND_UNIQUE_CONTACT_NUM CHECK (REGEXP_LIKE(CONTACT_NUM,'^[789][0-9]{9}$'))
);

CREATE TABLE Parts (
        P_ID VARCHAR2(5) PRIMARY KEY CONSTRAINT P_ID_MUST_START_WITH_P_AND_MUST_CONTAINS_4_DIGIT CHECK (P_ID LIKE 'P____'),
        P_NAME VARCHAR2(50),
        COLOR VARCHAR2(50),
        UNITE_RATE VARCHAR2(10) CONSTRAINT UNITE_RATE_MUST_BE_GREATERTHAN_0 CHECK (UNITE_RATE > 0 )
);

CREATE TABLE Catalog (
        S_ID VARCHAR2(5) REFERENCES Supplier,
        P_ID VARCHAR2(5) REFERENCES Parts,
        QTY VARCHAR2(25)
);

INSERT INTO Supplier VALUES ('S1234', 'Diana', 7845123069);

INSERT INTO Parts VALUES ('P5678', 'Wheel', 'Blue', 1);

INSERT INTO Catalog VALUES ('S1234', 'P5678', 'GOOD');