CREATE TABLE Doctor (
        DOCTOR_ID VARCHAR2(5) PRIMARY KEY CONSTRAINT DOCTOR_ID_MUST_START_WITH_D_AND_MUST_CONTAINS_4_DIGIT CHECK (DOCTOR_ID LIKE 'D____'),
        D_NAME VARCHAR2(50),
        D_EMAIL VARCHAR2(50) UNIQUE CONSTRAINT MUST_BE_ENTER_VALID_AND_UNIQUE_EMAIL_ID CHECK(D_EMAIL LIKE '__%@__%.__%'),
        SPECIALIZATION VARCHAR2(50),
        DEGREE VARCHAR2(50)
);

CREATE TABLE Patient (
        PATIENT_ID VARCHAR2(5) PRIMARY KEY CONSTRAINT PATIENT_ID_MUST_START_WITH_P_AND_MUST_CONTAINS_4_DIGIT CHECK (PATIENT_ID LIKE 'P____'),
        P_NAME VARCHAR2(50),
        P_CONTACT NUMBER(10) UNIQUE CONSTRAINT MUST_BE_ENTER_VALID_AND_UNIQUE_CONTACT_NUMBER CHECK (REGEXP_LIKE(P_CONTACT,'^[789][0-9]{9}$')),
        P_EMAIL VARCHAR2(50) UNIQUE CONSTRAINT MUST_BE_ENTER_VALID_AND_UNIQUE_EMAIL_ID CHECK(P_EMAIL LIKE '__%@__%.__%'),
        CITY VARCHAR2(50) PATIENT_NOT_BELONG_TO_DELHI_KOLKATA_GANDHINAGAR CHECK (UPPER (CITY) != 'DELHI','KOLKATA','GANDHINAGAR'),
);

CREATE TABLE Appointment (
        APPOINTMENT_ID NUMBER(10),
        DOCTOR_ID VARCHAR2(5) REFERENCES Doctor,
        PATIENT_ID VARCHAR2(5) REFERENCES Patient,
        AP_DATE TIMESTAMP, --CONSTRAINT AP_DATE_MUST_BE_AFTER_TODAYS_DATE CHECK (AP_DATE )
        DISEAS_INFO VARCHAR2(50)
);

INSERT INTO Doctor VALUES ('D1234', 'DR.CHARLIE', 'charlie@gmail.com', 'Neurosurgery', 'MBBS');

INSERT INTO Patient VALUES ('P1234', 'BOB' , 7896541230, 'bob@gmail.com', 'Canberra');

INSERT INTO Appointment VALUES (1, 'D1234', 'P1234', '12-SEP-2024', 'ABC');